#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  FR,             sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  FL,             sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  BR,             sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  BL,             sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ForKte,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_6,  ForKbe,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           Fr,            tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           Fl,            tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           Br,            tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           Bl,            tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port6,           ForKt,         tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port7,           ForKb,         tmotorVex393_MC29, openLoop, encoderPort, I2C_6)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// DATE == 10/27/18
/*
Fr = Front Right
Fl = Front Left
Br = Back Right
Bl = Back Left
ForK = Fork Lift
*/
int dp = 1;
//Func to stop motors
void stopMotors(){
	motor[Fr] = 0;
	motor[Fl] = 0;
	motor[Br] = 0;
	motor[Bl] = 0;
	motor[ForKt] = 0;
	motor[ForKb] = 0;
}
void drive(){
	switch(dp){
	case 1:
		motor[Fr] = vexRT[Ch2];
		motor[Br] = vexRT[Ch2];
		motor[Fl] = vexRT[Ch3];
		motor[Bl] = vexRT[Ch3];
		break;
	case 2:
		motor[Fr] = vexRT[Ch2]/2;
		motor[Br] = vexRT[Ch2]/2;
		motor[Fl] = vexRT[Ch3]/2;
		motor[Bl] = vexRT[Ch3]/2;
		break;
	case 3:
		motor[Fr] = vexRT[Ch2]*2;
		motor[Br] = vexRT[Ch2]*2;
		motor[Fl] = vexRT[Ch3]*2;
		motor[Bl] = vexRT[Ch3]*2;
		break;
	}
}
void ifs(){
	if(vexRT[Btn6U] == 1){
		motor[ForKt] = 127;
		motor[ForKb] = - 127;
	}
	if(vexRT[Btn6D] == 1){
		motor[ForKt] = - 127;
		motor[ForKb] = 127;
	}
	else{
		motor[ForKt] = 0;
		motor[ForKt] = 0;
	}
	if(vexRT[Btn8U] == 1){
		dp++;
	}
	if(vexRT[Btn8D] == 1){
		dp--;
	}
}

void clearLCD(){
	clearLCDLine(0);
	clearLCDLine(1);
}
void clearENC(){
	resetMotorEncoder(Fr);
  resetMotorEncoder(Fl);
  resetMotorEncoder(Br);
  resetMotorEncoder(Bl);
  resetMotorEncoder(ForKt);
  resetMotorEncoder(ForKb);
}
// This code is for the VEX cortex platform
#pragma platform(VEX2)
// Select Download method as "competition"
#pragma competitionControl(Competition)
//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	//This is my br atun clearing LCD and turning on backlight
	bStopTasksBetweenModes = false;
	bLCDBacklight = true;
	clearLCD();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
//Clearing the encoders before auton
clearENC();
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
/*
motor[Fr] = vexRT[Ch2];
motor[Br] = vexRT[Ch2];
motor[Fl] = vexRT[Ch3];
motor[Bl] = vexRT[Ch3];
*/
task usercontrol()
{
	while (true)
	{
		drive();
		ifs();
	}
}
/*
--------------------------------------------------------------------------------------------------------------------------------
*/
