#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Motor,  port2,           Fr,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Fl,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Bl,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Fork,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Br,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
void drive(int Fri,int Fli,int Bri,int Bli,int distance){
while(abs(getMotorEncoder(Bl))<distance){
motor[Fr] = Fri;
motor[Fl] = Fli;
motor[Br] = Bri;
motor[Bl] = Bli;
}
}

*/

void ifs(){
	if(vexRT[Btn8U] == 1){
		motor[Ball] = - 127;
	}
	else{
		motor[Ball] = 0;
	}
	if(vexRT[Btn5U] == 1){
		motor[Fork] = -45;
	}
	else if(vexRT[Btn5D] == 1){
		motor[Fork] =  45;
	}
	else{
		motor[Fork] = 0;
	}
}
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;

//Wait for Press--------------------------------------------------
void waitForPress()
{
	while (nLCDButtons == 0)
	{
	}
	wait1Msec(5);
}
//----------------------------------------------------------------

//Wait for Release------------------------------------------------
void waitForRelease()
{
	while (nLCDButtons != 0)
	{
	}
	wait1Msec(5);
}
int count = 0;
void stopMotors()
{
	motor[Fr] = 0;
	motor[Fl] = 0;
	motor[Br] = 0;
	motor[Bl] = 0;
}
void resetGyro()
{
	SensorType[in3] = sensorNone;
	wait1Msec(1000);
	SensorType[in3] = sensorGyro;
	wait1Msec(2000);
}
//Finction to turn whith gyro
void gyroTurn(int r, int l, int input)
{
	int deg = input * 100;
	while (SensorValue[in3] < deg)
	{
		motor[Fr] = r;
		motor[Fl] = l;
		motor[Br] = r;
		motor[Bl] = l;
	}
	stopMotors();
}
//function to move until button is pressed
void forwardd()
{
	motor[Fr] = 100;
	motor[Fl] = 100;
	motor[Br] = 100;
	motor[Bl] = 100;
}
//Makes robot go backward for auton
void backwardd()
{
	motor[Fr] = -100;
	motor[Fl] = -100;
	motor[Br] = -100;
	motor[Bl] = -100;
}
//Makes robot turn right for auton
void turnR()
{
	motor[Fr] = -100;
	motor[Fl] = 100;
	motor[Br] = -100;
	motor[Bl] = 100;
}
void turnL()
{
	motor[Fr] = 100;
	motor[Fl] = -100;
	motor[Br] = 100;
	motor[Bl] = -100;
}
void clearLCD()
{
	clearLCDLine(0);
	clearLCDLine(1);
}
// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	//starting milan
	// House keeping things.
	bDisplayCompetitionStatusOnLcd = false;
	bStopTasksBetweenModes = true;
	//Turning lcd backlight on
	bLCDBacklight = true;
	//clearing lcd
	clearLCD();
	//clearing encoders

	//------------- Beginning of User Interface Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Loop while center button is not pressed
	while (nLCDButtons != centerButton)
	{
		//Switch case that allows the user to choose from 4 different options
		switch (count)
		{
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "RED");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if (nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 3;
			}
			else if (nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 1:
			//Display second choice
			displayLCDCenteredString(0, "BLUE");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if (nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if (nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		}
	}
	clearLCD();
	displayLCDCenteredString(0, "Good Luck!!");
	displayLCDCenteredString(1, "Murphy's Law;)");
	resetGyro();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	resetGyro();
	switch (count)
	{
		//RED
	case 0:
		resetGyro();
		//Flag toggle
		forwardd();
		sleep(2000);
		stopMotors();
		//Getting in position for parking
		backwardd();
		sleep(2500);
		stopMotors();
		// turning twards platform
		//gyroTurn(-100,100,-9);
		turnR();
		sleep(1650);
		stopMotors();
		//Parking on platform
		forwardd();
		sleep(1700);
		stopMotors();
		break;
		//BLUE
	case 1:
		resetGyro();
		//Flag toggle
		forwardd();
		sleep(2000);
		stopMotors();
		//Getting in position for parking
		backwardd();
		sleep(2500);
		stopMotors();
		// turning twards platform
		turnL();
		sleep(1650);
		stopMotors();
		//Parking on platform
		forwardd();
		sleep(1700);
		stopMotors();
		break;
	}
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		//code for joystick buttons
		ifs();
		//code for joysticks
		motor[Fr] = vexRT[Ch2];
		motor[Br] = vexRT[Ch2];
		motor[Fl] = vexRT[Ch3];
		motor[Bl] = vexRT[Ch3];
	}
}
