#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Motor,  port2,           Fr,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Fl,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Bl,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Fork,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Br,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Fr = Front Right
Fl = Front Left
Br = Back Right
Bl = Back Left
ForK = Fork Lift
*/
//task to be lit
task milan(){
	while(1){
		displayLCDCenteredString(0,"Proud NRA");
		displayLCDCenteredString(1,"Member");
		sleep(2000);
		displayLCDCenteredString(0,"Prius Lives");
		displayLCDCenteredString(1,"Matter");
		sleep(2000);
	}
}
//Makes robot go forward for auton
void forward(){
	motor[Fr] = 127;
	motor[Fl] = 127;
	motor[Br] = 127;
	motor[Bl] = 127;
}
//Makes robot go backward for auton
void backward(){
	motor[Fr] = -127;
	motor[Fl] = -127;
	motor[Br] = -127;
	motor[Bl] = -127;
}
//Makes robot turn right for auton
void turnR(){
	motor[Fr] = -127;
	motor[Fl] = 127;
	motor[Br] = -127;
	motor[Bl] = 127;
}
//Makes robot stop for auton
void stopMotors(){
	motor[Fr] = 0;
	motor[Fl] = 0;
	motor[Br] = 0;
	motor[Bl] = 0;
}

void ifs(){
	if(vexRT[Btn6U] == 1){
		motor[Lift] = - 127;
	}
	else if(vexRT[Btn6D] == 1){
		motor[Lift] =  127;
	}
	else{
		motor[Lift] = 0;
	}
	if(vexRT[Btn5U] == 1){
		motor[Fork] = 60;
	}
	else if(vexRT[Btn5D] == 1){
		motor[Fork] =  -60;
	}
	else{
		motor[Fork] = 0;
	}
}
void clearLCD(){
	clearLCDLine(0);
	clearLCDLine(1);
}
// This code is for the VEX cortex platform
#pragma platform(VEX2)
// Select Download method as "competition"
#pragma competitionControl(Competition)
//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void pre_auton()
{
	//starting milan
	startTask(milan);
	// House keeping things.
	bDisplayCompetitionStatusOnLcd = false;
	bStopTasksBetweenModes = true;
	//Turning lcd backlight on
	bLCDBacklight = true;
	//clearing lcd
	clearLCD();

}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task autonomous(){
	stopTask(milan);
	//Flag toggle
	forward();
	sleep(2000);
	stopMotors();
	//Getting in position for parking
	backward();
	sleep(2500);
	stopMotors();
	// turning twards platform
	turnR();
	sleep(2000);
	stopMotors();
	//Parking on platform
	forward();
	sleep(2000);
	stopMotors();
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
/*
Extra driver cide in case it gets lost.
motor[Fr] = vexRT[Ch2];
motor[Br] = vexRT[Ch2];
motor[Fl] = vexRT[Ch3];
motor[Bl] = vexRT[Ch3];
*/
task usercontrol()
{
	startTask(milan);
	while (true)
	{
		//code for joystick buttons
		ifs();
		//code for joysticks
		motor[Fr] = vexRT[Ch2];
		motor[Br] = vexRT[Ch2];
		motor[Fl] = vexRT[Ch3];
		motor[Bl] = vexRT[Ch3];
	}
}
