#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in2,    Lf,             sensorLineFollower)
#pragma config(Sensor, dgtl1,  Button,         sensorTouch)
#pragma config(Motor,  port2,           Fr,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Fl,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Bl,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Fork,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Br,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Ball,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
void drive(int Fri,int Fli,int Bri,int Bli,int distance){
while(abs(getMotorEncoder(Bl))<distance){
motor[Fr] = Fri;
motor[Fl] = Fli;
motor[Br] = Bri;
motor[Bl] = Bli;
}
}

*/
bool ready = false;
int red = 0;
int blue = 0;
int gray = 0;
int count = 0;
//variables and functions for lcd
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
void ifs(){
	if(vexRT[Btn8U] == 1){
		motor[Ball] = - 127;
	}
	else{
		motor[Ball] = 0;
	}
	if(vexRT[Btn5U] == 1){
		motor[Fork] = -45;
	}
	else if(vexRT[Btn5D] == 1){
		motor[Fork] =  45;
	}
	else{
		motor[Fork] = 0;
	}
}
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}
//functon to clear lcd
void clearLCD(){
	clearLCDLine(0);
	clearLCDLine(1);
}
//finction to stop motors
void stopMotors(){
	motor[Fr] = 0;
	motor[Fl] = 0;
	motor[Br] = 0;
	motor[Bl] = 0;
}
//Function to reset gyro
void resetGyro(){
	SensorType[in1] = sensorNone;
	wait1Msec(1000);
	SensorType[in1] = sensorGyro;
	wait1Msec(2000);
}
//Finction to turn whith gyro
void gyroTurn(int r,int l,int input){
	int deg = input*100;
	while(SensorValue[in1] < deg){
		motor[Fr] = r;
		motor[Fl] = l;
		motor[Br] = r;
		motor[Bl] = l;
	}
	stopMotors();
}
//function to move until button is pressed
void buttMove(int r,int l,int inc){
	int count = 0;
	while(inc != count){
		if(SensorValue[Button] == 1){
			count++;
		}
		motor[Fr] = r;
		motor[Br] = r;
		motor[Fl] = l;
		motor[Bl] = l;
	}
	stopMotors();
}
//Line follower functions
void redMove(int r,int l){
	while(SensorValue[Lf] < red){
		motor[Fr] = r;
		motor[Br] = r;
		motor[Fl] = l;
		motor[Bl] = l;
	}
	stopMotors();
}
void blueMove(int r,int l){
	while(SensorValue[Lf] < blue){
		motor[Fr] = r;
		motor[Br] = r;
		motor[Fl] = l;
		motor[Bl] = l;
	}
	stopMotors();
}
void grayMove(int r,int l){
	while(SensorValue[Lf] < gray){
		motor[Fr] = r;
		motor[Br] = r;
		motor[Fl] = l;
		motor[Bl] = l;
	}
	stopMotors();
}
void goBall(int speed,int time){
	motor[Ball] = speed;
	sleep(time);
}
// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
	ready = false;
	clearLCDLine(0);
	clearLCDLine(1);
	//Loop while center button is not pressed
	while(ready == false)
	{
		//Switch case that allows the user to choose from 4 different options
		switch(count){
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "do u need cal ??");
			displayLCDCenteredString(1, "Yes		        No");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			else if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 3;
			}
			break;
		case 1:
			//Display second choice
			displayLCDCenteredString(0, "BLUE");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			else if(nLCDButtons == centerButton)
			{
				waitForRelease();
				ready = true;
			}
			break;
		case 2:
			//Display first choice
			displayLCDCenteredString(0, "RED");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			else if(nLCDButtons == centerButton)
			{
				waitForRelease();
				ready = true;
			}
			break;
		case 3:
			displayLCDCenteredString(0, "LF cal red");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			else if(nLCDButtons == centerButton){
				waitForRelease();
				red = SensorValue[in2];
			}
			break;
		case 4:
			displayLCDCenteredString(0, "LF cal blue");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			else if(nLCDButtons == centerButton){
				waitForRelease();
				blue = SensorValue[in2];
			}
			break;
		case 5:
			displayLCDCenteredString(0, "LF cal gray");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			else if(nLCDButtons == centerButton){
				waitForRelease();
				gray = SensorValue[in2];
				count = 1;
			}
			break;
		default:
			//Display second choice
			displayLCDCenteredString(0, "BLUE");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			else if(nLCDButtons == centerButton)
			{
				waitForRelease();
				ready = true;
			}
			break;

		}
	}
	clearLCD();
	displayLCDCenteredString(0, "Good Luck!!");
	displayLCDCenteredString(1, "Murphy's Law;)");

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	resetGyro();
	switch(count){
		//BLUE
	case 1:
		motor[Fr] = 100;
		motor[Fl] = 100;
		motor[Br] = 100;
		motor[Bl] = 100;
		sleep(3000);
		stopMotors();
		break;
		//RED
	case 2:
		motor[Fr] = 100;
		motor[Fl] = 100;
		motor[Br] = 100;
		motor[Bl] = 100;
		sleep(3000);
		stopMotors();
		break;
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		//code for joystick buttons
		ifs();
		//code for joysticks
		motor[Fr] = vexRT[Ch2];
		motor[Br] = vexRT[Ch2];
		motor[Fl] = vexRT[Ch3];
		motor[Bl] = vexRT[Ch3];
	}
}
